# 可选 没有的话以文件名为name
name: learn-github-actions

# 可选 类似说明
run-name: ${{ github.actor }} is learning GitHub Actions

# 触发动作
on:
  workflow_dispatch:
    #inputs:
     # sname:
       # required: false
      #  type: string
      #  default: 'domain/namespace/name:tag'

env:
  REGION: cn-north-4
      

# job集
jobs:

  # 自定义job名
  j1:

    # job运行环境
    runs-on: ubuntu-latest
    
    # 步骤集
    steps:

      # actions仓库地址 https://github.com/actions/
      - name: checkout # 可选 step name
        uses: actions/checkout@v4 # 引用actions
        with: # 参考action库说明
          clean: true

      # 上下文
      #- name: Dump GitHub context
      #  env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      #  run: echo "$GITHUB_CONTEXT"
        
      #- name: change seporate
      #  run: echo ${{inputs.sname}} | tr '/' '_'

      - name: Set GH_ENV
        run: >
          echo "tokk: tkv" >> "$GITHUB_ENV"

      - name: get tokk
        run: echo $tokk
