# 可选 没有的话以文件名为name
name: learn-github-actions

# 可选 类似说明
run-name: ${{ github.actor }} is learning GitHub Actions

# 触发动作
on: [push]

# job集
jobs:

  # 自定义job名
  check-bats-version:

    # job运行环境
    runs-on: ubuntu-latest

    # 步骤集
    steps:

      # actions仓库地址 https://github.com/actions/
      - uses: actions/checkout@v4 # 引用actions

      # 使用node14
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      # 运行命令
      - run: npm install -g bats
      - run: bats -v
