# 可选 没有的话以文件名为name
name: learn-github-actions

# 可选 类似说明
run-name: ${{ github.actor }} is learning GitHub Actions

# 触发动作
on: [push]

# job集
jobs:

  # 自定义job名
  check-bats-version:

    # job运行环境
    runs-on: ubuntu-latest

    # 可选 默认工作目录
    #defaults:
    #  run:
    #    working-directory: ./scripts
    
    # 步骤集
    steps:

      # actions仓库地址 https://github.com/actions/
      - name: checkout # 可选 step name
        uses: actions/checkout@v4 # 引用actions
        with: # 参考action库说明
          clean: true

      # 运行命令
      - run: echo "$ENAME"
        env:
          ENAME: fish

      # 上下文
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: vars
        env:
          VARS: ${{ toJson(vars) }}
        run: echo "$VARS"
